required_columns = [
        'body_el',
        'body_ev'
        ]
columns_to_drop = [
        'body__cbt',
        'body__cst',
        'body__gbt',
        'body__gst',
        'body__r',
        'body__s',
        'body__u',
        'body__utma',
        'body__utmht',
        'body__utmz',
        'body__v',
        'body_a',
        'body_clt',
        'body_dit',
        'body_dns',
        'body_gjid',
        'body_gtm',
        'body_jid', # needed for linking data between doubleclick and ga
        'body_pdt', # page download times
        'body_plt', # page load times
        'body_rrt', # redirect response time
        'body_srt', # server response time
        'body_tcp', # tcp connect time
        ]
# _ga 2 years to identify a visitor
# _gi 24 hours user journey
# _gat 10 minutes throttling request rate

new_columns_ga360_dimensions = [
        'fullVisitorId',
        'visitId',
        'visitNumber',
        'visitStartTime'
        'date',
        'trafficSource_referralPath',
        'trafficSource_campaign',
        'trafficSource_source',
        'trafficSource_medium',
        'trafficSource_keyword',
        'trafficSource_adContent',
        'trafficSource_adwordsCkickInfo_campaignId',
        'trafficSource_adwordsClickInfo_adGroupId',
        'trafficSource_adwordsClickInfo_creativeId',
        'trafficSource_adwordsClickInfo_criteriaId',
        'trafficSource_adwordsClickInfo_page',
        'trafficSource_adwordsClickInfo_slot',
        'trafficSource_adwordsClickInfo_criteriaParameters',
        'trafficSource_adwordsClickInfo_gclid',
        'trafficSource_adwordsClickInfo_customerId',
        'trafficSource_adwordsClickInfo_adNetworkType',
        'trafficSource_adwordsClickInfo_targetingCriteria_boomUserlistId',
        'trafficSource_adwordsClickInfo_isVideoAd',
        'trafficSource_isTrueDirect',
        'trafficSource_campaignCode',
        'geoNetwork_continent',
        'geoNetwork_subContinent',
        'geoNetwork_country',
        'geoNetwork_region',
        'geoNetwork_metro',
        'geoNetwork_city',
        'geoNetwork_cityId',
        'geoNetwork_networkDomain',
        'geoNetwork_latitude',
        'geoNetwork_longitude',
        'geoNetwork_networkLocation',
        'device_browser',
        'device_browserVersion',
        'device_browserSize',
        'device_operatingSystem',
        'device_operatingSystemVersion',
        'device_isMobile',
        'device_mobileDeviceBranding',
        'device_mobileDeviceMobile',
        'device_mobileInputSelector',
        'device_mobileDeviceInfo',
        'device_mobileDeviceMarketingName',
        'device_flashVersion',
        'device_javaEnabled',
        'device_language',
        'device_screenColors',
        'device_screenResolution',
        'device_deviceCategory',
        'landingPage'
        ]

new_columns_ga360_hits_events = [
        'fullVisitorId',
        'visitId',
        'visitNumber',
        'visitStartTime',
        'hits_eventInfo_eventCategory',
        'hits_eventInfo_eventAction',
        'hits_eventInfo_eventLabel',
        'hits_eventInfo_eventValue',
        'hits_hitNumber',
        'hits_type'
        ]

new_columns_ga360_hits_ecommerce = [
        'fullVisitorId',
        'visitId',
        'visitStartTime',
        'hits_hitNumber',
        'hits_time',
        'hits_hour',
        'hits_minute',
        'hits_isSecure',
        'hits_isInteractive',
        'hits_referer',
        'hits_page_pagePath',
        'hits_page_hostname',
        'hits_page_pageTitle',
        'hits_page_searchKeyword',
        'hits_page_searchCategory',
        'hits_page_pagePathLevel1',
        'hits_page_pagePathLevel2',
        'hits_page_pagePathLevel3',
        'hits_page_pagePathLevel4',
        'hits_item_transactionId',
        'hits_item_productName',
        'hits_item_productCategory',
        'hits_item_productSku',
        'hits_item_itemQuantity',
        'hits_item_itemRevenue',
        'hits_item_currencyCode',
        'hits_item_localItemRevenue',
        'hits_product_productPrice',
        'hits_product_productQuantity',
        'hits_product_productRefundAmount',
        'hits_product_productRevenue',
        'hits_product_productSKU',
        'hits_product_productVariant',
        'hits_eventInfo_eventCategory',
        'hits_eventInfo_eventAction',
        'hits_eventInfo_eventLabel',
        'hits_eventInfo_eventValue',
        'hit_type'
        ]
