columns_to_drop = [
        'body__cbt',
        'body__cst',
        'body__gbt',
        'body__gst',
        'body__r',
        'body__s',
        'body__u',
        'body__utma',
        'body__utmht',
        'body__utmz',
        'body__v',
        'body_a',
        'body_clt',
        'body_dit',
        'body_dns',
        'body_gjid',
        'body_gtm',
        'body_jid', # needed for linking data between doubleclick and ga
        'body_ni', # specifies that a hit be considered non-interactive
        'body_pdt', # page download times
        'body_plt', # page load times
'body_pr10ca', 'body_pr10cc', 'body_pr10id', 'body_pr10nm', 'body_pr10pr', 'body_pr10qt', 'body_pr10va', 'body_pr11ca', 'body_pr11cc', 'body_pr11id', 'body_pr11nm', 'body_pr11pr', 'body_pr11qt', 'body_pr11va', 'body_pr12ca', 'body_pr12cc', 'body_pr12id', 'body_pr12nm', 'body_pr12pr', 'body_pr12qt', 'body_pr12va', 'body_pr13ca', 'body_pr13cc', 'body_pr13id', 'body_pr13nm', 'body_pr13pr', 'body_pr13qt', 'body_pr13va', 'body_pr14ca', 'body_pr14id', 'body_pr14nm', 'body_pr14pr', 'body_pr14qt', 'body_pr14va', 'body_pr15ca', 'body_pr15id', 'body_pr15nm', 'body_pr15pr', 'body_pr15qt', 'body_pr15va', 'body_pr16ca', 'body_pr16id', 'body_pr16nm', 'body_pr16pr', 'body_pr16qt', 'body_pr16va', 'body_pr17ca', 'body_pr17id', 'body_pr17nm', 'body_pr17pr', 'body_pr17qt', 'body_pr17va', 'body_pr18ca', 'body_pr18id', 'body_pr18nm', 'body_pr18pr', 'body_pr18qt', 'body_pr18va', 'body_pr19ca', 'body_pr19id', 'body_pr19nm', 'body_pr19pr', 'body_pr19qt', 'body_pr19va', 'body_pr1ca', 'body_pr1cc', 'body_pr1id', 'body_pr1nm', 'body_pr1pr', 'body_pr1qt', 'body_pr1va', 'body_pr20ca', 'body_pr20id', 'body_pr20nm', 'body_pr20pr', 'body_pr20qt', 'body_pr20va', 'body_pr2ca', 'body_pr2cc', 'body_pr2id', 'body_pr2nm', 'body_pr2pr', 'body_pr2qt', 'body_pr2va', 'body_pr3ca', 'body_pr3cc', 'body_pr3id', 'body_pr3nm', 'body_pr3pr', 'body_pr3qt', 'body_pr3va', 'body_pr4ca', 'body_pr4cc', 'body_pr4id', 'body_pr4nm', 'body_pr4pr', 'body_pr4qt', 'body_pr4va', 'body_pr5ca', 'body_pr5cc', 'body_pr5id', 'body_pr5nm', 'body_pr5pr', 'body_pr5qt', 'body_pr5va', 'body_pr6ca', 'body_pr6cc', 'body_pr6id', 'body_pr6nm', 'body_pr6pr', 'body_pr6qt', 'body_pr6va', 'body_pr7ca', 'body_pr7cc', 'body_pr7id', 'body_pr7nm', 'body_pr7pr', 'body_pr7qt', 'body_pr7va', 'body_pr8ca', 'body_pr8cc', 'body_pr8id', 'body_pr8nm', 'body_pr8pr', 'body_pr8qt', 'body_pr8va', 'body_pr9ca', 'body_pr9cc', 'body_pr9id', 'body_pr9nm', 'body_pr9pr', 'body_pr9qt', 'body_pr9va'
        ]
# _ga 2 years to identify a visitor
# _gi 24 hours user journey
# _gat 10 minutes throttling request rate

new_columns_ga360_dimensions = [
        'fullVisitorId',
        'visitId',
        'visitNumber',
        'visitStartTime'
        'date',
        'trafficSource_referralPath',
        'trafficSource_campaign',
        'trafficSource_source',
        'trafficSource_medium',
        'trafficSource_keyword',
        'trafficSource_adContent',
        'trafficSource_adwordsCkickInfo_campaignId',
        'trafficSource_adwordsClickInfo_adGroupId',
        'trafficSource_adwordsClickInfo_creativeId',
        'trafficSource_adwordsClickInfo_criteriaId',
        'trafficSource_adwordsClickInfo_page',
        'trafficSource_adwordsClickInfo_slot',
        'trafficSource_adwordsClickInfo_criteriaParameters',
        'trafficSource_adwordsClickInfo_gclid',
        'trafficSource_adwordsClickInfo_customerId',
        'trafficSource_adwordsClickInfo_adNetworkType',
        'trafficSource_adwordsClickInfo_targetingCriteria_boomUserlistId',
        'trafficSource_adwordsClickInfo_isVideoAd',
        'trafficSource_isTrueDirect',
        'trafficSource_campaignCode',
        'geoNetwork_continent',
        'geoNetwork_subContinent',
        'geoNetwork_country',
        'geoNetwork_region',
        'geoNetwork_metro',
        'geoNetwork_city',
        'geoNetwork_cityId',
        'geoNetwork_networkDomain',
        'geoNetwork_latitude',
        'geoNetwork_longitude',
        'geoNetwork_networkLocation',
        'device_browser',
        'device_browserVersion',
        'device_browserSize',
        'device_operatingSystem',
        'device_operatingSystemVersion',
        'device_isMobile',
        'device_mobileDeviceBranding',
        'device_mobileDeviceMobile',
        'device_mobileInputSelector',
        'device_mobileDeviceInfo',
        'device_mobileDeviceMarketingName',
        'device_flashVersion',
        'device_javaEnabled',
        'device_language',
        'device_screenColors',
        'device_screenResolution',
        'device_deviceCategory',
        'landingPage'
        ]

new_columns_ga360_hits_events = [
        'fullVisitorId',
        'visitId',
        'visitNumber',
        'visitStartTime',
        'hits_eventInfo_eventCategory',
        'hits_eventInfo_eventAction',
        'hits_eventInfo_eventLabel',
        'hits_eventInfo_eventValue',
        'hits_hitNumber',
        'hits_type'
        ]

new_columns_ga360_hits_ecommerce = [
        'fullVisitorId',
        'visitId',
        'visitStartTime',
        'hits_hitNumber',
        'hits_time',
        'hits_hour',
        'hits_minute',
        'hits_isSecure',
        'hits_isInteractive',
        'hits_referer',
        'hits_page_pagePath',
        'hits_page_hostname',
        'hits_page_pageTitle',
        'hits_page_searchKeyword',
        'hits_page_searchCategory',
        'hits_page_pagePathLevel1',
        'hits_page_pagePathLevel2',
        'hits_page_pagePathLevel3',
        'hits_page_pagePathLevel4',
        'hits_item_transactionId',
        'hits_item_productName',
        'hits_item_productCategory',
        'hits_item_productSku',
        'hits_item_itemQuantity',
        'hits_item_itemRevenue',
        'hits_item_currencyCode',
        'hits_item_localItemRevenue',
        'hits_product_productPrice',
        'hits_product_productQuantity',
        'hits_product_productRefundAmount',
        'hits_product_productRevenue',
        'hits_product_productSKU',
        'hits_product_productVariant',
        'hits_eventInfo_eventCategory',
        'hits_eventInfo_eventAction',
        'hits_eventInfo_eventLabel',
        'hits_eventInfo_eventValue',
        'hit_type'
        ]
